### ISSUE TITLE
关于音量和任务栏缩略图

### ISSUE THREAD

**Issue by ucrt1** [WuXiaoMuer/Mim-Music#1]
软件启动时会将系统音量调到最大，任务栏缩略图在高dpi下显示不正常

**Comment by WuXiaoMuer** [comment]
[+] 修复部分状态下任务栏缩略图错误问题
（人话：DwmSetIconicThumbnail）
[+] 优化缩略图显示性能问题；
（原有位图处理改为逐像素迁移）
（消息处理改为切歌时自动更新）
[+] 子类化问题
[+] 圆角化问题

**Comment by WuXiaoMuer** [comment]
https://github.com/WuXiaoMuer/Mim-Music/releases/tag/v1.5.1
![VS`VESGDN99H8UO8CYSMQ`S](https://user-images.githubusercontent.com/80154839/198838577-80956b68-a617-4530-b5da-5b924e0024ab.png)
![IWB2IMT60UO7FPZ 1I6GDLV](https://user-images.githubusercontent.com/80154839/198838596-154a1065-93d7-4edc-957c-0b9499304ceb.jpg)
